version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: myapp

volumes:
  dbdata:
